name: Maven CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  support_java_lts_versions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: 📦 Install dependencies
        run: mvn install
      - name: 🧪 Run tests with coverage
        run: mvn test

  codacy_coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      # https://github.com/actions/setup-java?tab=readme-ov-file#caching-packages-dependencies
      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: 📦 Install dependencies
        run: mvn install
      - name: 🧪 Run tests with coverage
        run: mvn test
      - name: 🤖 Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: target/site/jacoco/jacoco.xml